### ISSUE TITLE
Issue #13 Instalación de OpenCart

### ISSUE THREAD

**Issue by fiturbe** [mosoriob/inf-323-questions#3]
Descargamos los archivos correspondientes de OpenCart en el directorio /srv/www/opencart/, dimos los permisos correspondientes y al querer [ingresar](grupo01.mosorio.me) por el explorador para iniciar la instalación lanza un error 500 el cual no da mayor información, al revisar el log de nginx sale lo siguiente:
`2017/10/16 17:56:43 [error] 15222#15222: send() failed (111: Connection refused) while resolving, resolver: 10.10.15.200:53` 
¿Qué puede ser?

**Comment by mosoriob** [comment]
Tenian dos listen, uno para tcp y uno para el socks (es uno u otro)
Entonces cuando probaban el tcp tenian problemas
```
[root@grupo01-m1 ~]# curl 127.0.0.1:9000
curl: (7) Failed connect to 127.0.0.1:9000; Connection refused
```

Ahi está la configuración anterior
```
listen = 127.0.0.1:9000
; WARNING: If you switch to a unix socket, you have to grant your webserver user
;          access to that socket by setting listen.acl_users to the webserver user.
listen = /var/run/php-fpm/php-fpm.sock
```

Ahora si escucha solo en el puerto

```
[root@grupo01-m1 ~]# curl 127.0.0.1:9000
curl: (56) Recv failure: Connection reset by peer
```

Me comentan.

**Comment by fiturbe** [comment]
@sirspock cierto, comenté el otro ya que está configurado para funcionar con `listen = /var/run/php-fpm/php-fpm.sock`, ahora bien el problema que surge es al intentar instalar OpenCart, lanza un error 500, habilité la opción para mostrar los errores y muestra los siguientes warning y errores:
```
Warning: fopen(/srv/www/opencart/system/storage/logs/error.log): failed to open stream: Permission denied in /srv/www/opencart/system/library/log.php on line 22
Warning: fopen(/srv/www/opencart/system/storage/logs/openbay.log): failed to open stream: Permission denied in /srv/www/opencart/system/library/log.php on line 22
Warning: fwrite() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/log.php on line 31

Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to create the cache directory (/srv/www/opencart/system/storage/cache/36).' in /srv/www/opencart/system/library/template/Twig/Cache/Filesystem.php:62 Stack trace: #0 /srv/www/opencart/system/library/template/Twig/Environment.php(400): Twig_Cache_Filesystem->write('/srv/www/openca...', '<?php\n\n/* commo...') #1 /srv/www/opencart/system/library/template/twig.php(33): Twig_Environment->loadTemplate('common/footer.t...') #2 /srv/www/opencart/system/library/template.php(51): Template\Twig->render('common/footer', true) #3 /srv/www/opencart/system/engine/loader.php(125): Template->render('common/footer', true) #4 /srv/www/opencart/install/controller/common/footer.php(11): Loader->view('common/footer', Array) #5 [internal function]: ControllerCommonFooter->index(Array) #6 /srv/www/opencart/system/engine/action.php(79): call_user_func_array(Array, Array) #7 /srv/www/opencart/system/engine/loader.php(48): Action->execute(Object(Registry), Array) #8 /srv/www/o in /srv/www/opencart/system/library/template/Twig/Cache/Filesystem.php on line 62
Warning: fopen(/srv/www/opencart/system/storage/session//sess_5c2f9e1ab16e9298c473f7f2f6): failed to open stream: Permission denied in /srv/www/opencart/system/library/session/file.php on line 29
Warning: fwrite() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/log.php on line 31
Warning: flock() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/session/file.php on line 31
Warning: fwrite() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/log.php on line 31
Warning: fwrite() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/session/file.php on line 33
Warning: fwrite() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/log.php on line 31
Warning: fflush() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/session/file.php on line 35
Warning: fwrite() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/log.php on line 31
Warning: flock() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/session/file.php on line 37
Warning: fwrite() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/log.php on line 31
Warning: fclose() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/session/file.php on line 39
Warning: fwrite() expects parameter 1 to be resource, boolean given in /srv/www/opencart/system/library/log.php on line 31
```
Los warning parecieran ser problemas de permisos, reviso las carpetas y los archivos y tienen (creo) los permisos necesarios, en cambio para el error he buscado en todos lados y no he encontrado solución.

**Comment by mosoriob** [comment]
Es un problema de permisos, php-fpm tiene problemas para leer los archivos. Como tus archivos tienen permisos para nginx, cambie los permisos a nginx.

Ahora solo tienes problemas con los logs, que tienen  permisos root.

Adjunto el git diff
```
[root@grupo01-m1 etc]# git diff
diff --git a/php-fpm.d/www.conf b/php-fpm.d/www.conf
index 8d6fc0a..63c9eb0 100644
--- a/php-fpm.d/www.conf
+++ b/php-fpm.d/www.conf
@@ -20,8 +20,8 @@
 ; Unix user/group of processes
 ; Note: The user is mandatory. If the group is not set, the default user's group
 ;       will be used.
-user = php-fpm
-group = php-fpm
+user = nginx
+group = nginx

 ; The address on which to accept FastCGI requests.
 ; Valid syntaxes are:
```

**Comment by fiturbe** [comment]
Perfecto! Los warning también se solucionó mediante `chown -R nginx:nginx /srv/www/opencart/system/storage/logs`.
Gracias!
